djangooo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

nom_projet/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('djangooo/', include("djangooo.urls")),
    path('travel/', include("travel_planner.urls")),
    path('admin/', admin.site.urls),
]

travel_planner/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('voyage/<int:voyage_id>/', views.detail_voyage, name='detail_voyage'),
    path('liste_voyages/', views.liste_voyages, name='liste_voyages'),
    path('search_voyage/', views.search_voyage, name='search_voyage'),
    path('liste_hebergements/', views.liste_hebergements, name='liste_hebergements'),
    path('search_hebergement/', views.search_hebergement, name='search_hebergement'),
    path('detail_hebergement/<int:hebergement_id>/', views.detail_hebergement, name='detail_hebergement'),
    path('search_destination/', views.search_destination, name='search_destination'),
    path('destination/', views.destination, name='destination'),
    path('ajouter_reservation_hebergement/<int:hebergement_id>/', views.ajouter_reservation_hebergement, name='ajouter_reservation_hebergement'),
    path('choix_reservation/', views.choix_reservation, name='choix_reservation'),
    path('mes_reservations_voyages/', views.mes_reservations_voyages, name='mes_reservations_voyages'),
    path('mes_reservations_hebergements/', views.mes_reservations_hebergements, name='mes_reservations_hebergements'),
    path('reservation_voyage/<int:voyage_id>/', views.detail_reservation_voyage, name='reservation_voyage'),
    path('reservation_hebergement/<int:hebergement_id>/', views.detail_reservation_hebergement, name='reservation_hebergement'),
    path('supprimer_reservation/<int:reservation_id>/', views.supprimer_reservation, name='supprimer_reservation'),
    path('ajouter_reservation_voyage/<int:voyage_id>/', views.ajouter_reservation_voyage, name='ajouter_reservation_voyage'),
    path('dashboard', views.dashboard, name='dashboard'),
    path("", views.index, name="index"),
]

travel_planner/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

class Voyage(models.Model):
    TRAIN = 'TR'
    AVION = 'AV'
    VOITURE = 'VO'
    TRANSPORT_CHOICES = [
        (TRAIN, 'Train'),
        (AVION, 'Avion'),
        (VOITURE, 'Voiture'),
    ]
    
    titre = models.CharField(max_length=100, blank=False)
    date_depart = models.DateTimeField(blank=False, default=timezone.now)
    date_arrivee = models.DateTimeField(blank=False, default=timezone.now)
    ville_depart = models.CharField(max_length=100, blank=False)
    ville_arrivee = models.CharField(max_length=100, blank=False)
    lieu_depart = models.CharField(max_length=100, blank=True)
    lieu_arrivee = models.CharField(max_length=100, blank=True)
    mode_transport = models.CharField(max_length=2, choices=TRANSPORT_CHOICES, blank=False)
    prix = models.DecimalField(max_digits=10, decimal_places=2, blank=False, default=0.00)
    date_retour = models.DateTimeField(blank=True, null=True)

    def is_aller_simple(self):
        return self.date_retour is None

    def __str__(self):
        return self.titre

    
class Hebergement(models.Model):
    HOTEL = 'HO'
    AUBERGE = 'AU'
    CHAMBRE_HOTE = 'CH'
    HÉBERGEMENT_CHOICES = [
        (HOTEL, 'Hôtel'),
        (AUBERGE, 'Auberge'),
        (CHAMBRE_HOTE, 'Chambre d\'hôte'),
    ]
    
    nom = models.CharField(max_length=100, blank=False)
    type_hebergement = models.CharField(max_length=2, choices=HÉBERGEMENT_CHOICES, blank=False)
    ville = models.CharField(max_length=100, blank=False)
    adresse = models.CharField(max_length=200, blank=False) 
    prix_nuit = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    nombre_chambres_disponibles = models.IntegerField(default=0)

    def __str__(self):
        return self.nom

class Reservation(models.Model):
    voyage = models.ForeignKey(Voyage, on_delete=models.CASCADE, null=True, blank=True)
    hebergement = models.ForeignKey(Hebergement, on_delete=models.CASCADE, null=True, blank=True)
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    date_reservation = models.DateTimeField(auto_now_add=True)
    nombre_personnes = models.IntegerField(default=1)

    def __str__(self):
        if self.voyage:
            return f"Réservation pour le voyage {self.voyage} - {self.utilisateur.username}"
        elif self.hebergement:
            return f"Réservation pour l'hébergement {self.hebergement} - {self.utilisateur.username}"
        else:
            return f"Réservation sans voyage ni hébergement - {self.utilisateur.username}"

travel_planner/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from .models import Hebergement, Voyage, Reservation
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import logout as django_logout

@login_required
def liste_voyages(request):
    voyages = Voyage.objects.all()
    return render(request, 'voyage/liste_voyages.html', {'voyages': voyages})

@login_required
def search_voyage(request):
    query = request.GET.get('q')
    if query:
        voyages = Voyage.objects.filter(
            Q(titre__icontains=query) | 
            Q(ville_depart__icontains=query) |
            Q(ville_arrivee__icontains=query)
        )
    else:
        voyages = Voyage.objects.all()
    return render(request, 'voyage/liste_voyages.html', {'voyages': voyages})

@login_required
def detail_voyage(request, voyage_id):  
    voyage = Voyage.objects.get(id=voyage_id)
    return render(request, 'voyage/detail_voyage.html', {'voyage': voyage})

@login_required
def detail_reservation_voyage(request, voyage_id):
    voyage = Voyage.objects.get(id=voyage_id)
    return render(request, 'reservation/detail_reservation_voyage.html', {'voyage': voyage})

@login_required
def detail_reservation_hebergement(request, hebergement_id):
    hebergement = Hebergement.objects.get(id=hebergement_id)
    return render(request, 'reservation/detail_reservation_hebergement.html', {'hebergement': hebergement})

@login_required
def choix_reservation(request):
    reservations = Reservation.objects.filter(utilisateur=request.user)
    return render(request, 'reservation/choix_reservation.html', {'reservations': reservations})

@login_required
def mes_reservations_voyages(request):
    reservations = Reservation.objects.filter(utilisateur=request.user)
    return render(request, 'reservation/mes_reservations_voyages.html', {'reservations': reservations})

@login_required
def mes_reservations_hebergements(request):
    reservations = Reservation.objects.filter(utilisateur=request.user)
    return render(request, 'reservation/mes_reservations_hebergements.html', {'reservations': reservations})

@login_required
def supprimer_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, pk=reservation_id)
    reservation.delete()
    return redirect('choix_reservation')

@login_required
def ajouter_reservation_voyage(request, voyage_id):
    if request.method == 'POST':
        voyage = get_object_or_404(Voyage, pk=voyage_id)
        Reservation.objects.create(voyage=voyage, utilisateur=request.user)
        return HttpResponseRedirect(reverse('mes_reservations_voyages'))

@login_required
def ajouter_reservation_hebergement(request, hebergement_id):
    if request.method == 'POST':
        hebergement = get_object_or_404(Hebergement, pk=hebergement_id)
        Reservation.objects.create(hebergement=hebergement, utilisateur=request.user)
        return HttpResponseRedirect(reverse('mes_reservations_hebergements'))
    
@login_required
def liste_hebergements(request):
    hebergements = Hebergement.objects.all()
    return render(request, 'hebergement/liste_hebergements.html', {'hebergements': hebergements})

@login_required
def search_hebergement(request):
    query = request.GET.get('q')
    if query:
        hebergements = Hebergement.objects.filter(Q(ville__icontains=query))
    else:
        hebergements = Hebergement.objects.all()
    return render(request, 'hebergement/liste_hebergements.html', {'hebergements': hebergements})

@login_required
def detail_hebergement(request, hebergement_id):
    hebergement = Hebergement.objects.get(id=hebergement_id)
    return render(request, 'hebergement/detail_hebergement.html', {'hebergement': hebergement})

@login_required
def destination(request):
    return render(request, 'destination/destination.html',)

@login_required
def search_destination(request):
    query = request.GET.get('q')
    voyages = Voyage.objects.filter(Q(ville_depart__icontains=query) | Q(ville_arrivee__icontains=query))
    hebergements = Hebergement.objects.filter(ville__icontains=query)

    return render(request, 'destination/destination.html', {'voyages': voyages, 'hebergements': hebergements, 'query': query}) 

@login_required
def index(request):
    username = request.user.username
    return render(request, 'index.html', {'username': username})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Invalid username or password.')
            return render(request, 'authentification/login.html')
    elif request.method == 'GET':
        return render(request, 'authentification/login.html')

def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'authentification/signup.html', {'form': form})

def redirect_login(request):
    return render(request, 'dashboard.html')

def my_logout(request):
    django_logout(request)
    return redirect('login')

def dashboard(request):
    return render(request, 'dashboard.html')

travel_planner/templates/reservation/choix_reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choix reservation</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Vos reservations</h1>
        <div class="links">
            <a href="{% url 'mes_reservations_voyages' %}">Mes voyages</a>
            <a href="{% url 'mes_reservations_hebergements' %}">Mes hebergements</a>
        </div>
        <a href="{% url 'index' %}" class="retour">Retour</a>
    </div>
</body>
</html>

travel_planner/templates/reservation/detail_reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails du voyage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Détails du voyage :</h1>
        <div class="details-box">
            <h2>{{ voyage.titre }}</h2>
            <br>
            <p><strong>Date de départ:</strong> {{ voyage.date_depart|date:"d/m/Y à H:i" }}</p>
            <p><strong>Date de retour:</strong> {{ voyage.date_arrivee|date:"d/m/Y à H:i" }}</p>
            <br>
            <p><strong>Départ:</strong> {{ voyage.lieu_depart }}</p>
            <p><strong>Arrivée:</strong> {{ voyage.lieu_arrivee }}</p>
            <br>
            {% if voyage.mode_transport %}
                {% if voyage.mode_transport == "TR" %}
                    <p><strong>Mode de transport:</strong> Train</p>
                {% elif voyage.mode_transport == "AV" %}
                    <p><strong>Mode de transport:</strong> Avion</p>
                {% elif voyage.mode_transport == "VO" %}
                    <p><strong>Mode de transport:</strong> Voiture</p>
                {% else %}
                    <p><strong>Mode de transport:</strong> Inconnu</p>
                {% endif %}
            {% endif %}
            <br>
            <p><strong>Prix:</strong> {{ voyage.prix }} €</p>
        </div>
        <a href="{% url 'mes_reservations_voyage' %}" class="retour">Retour</a>
    </div>
</body>
</html>

travel_planner/templates/reservation/detail_reservation_hebergement.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails de l'hébergement</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Détails de l'hébergement :</h1>
        <div class="details-box">
            <h2>{{ hebergement.nom }}</h2>
            <br>
            <p><strong>Type:</strong> {{ hebergement.get_type_hebergement_display }}</p>
            <p><strong>Ville:</strong> {{ hebergement.ville }}</p>
            <p><strong>Adresse:</strong> {{ hebergement.adresse }}</p>
            <p><strong>Prix par nuit:</strong> {{ hebergement.prix_nuit }} €</p>
            <p><strong>Nombre de chambres disponibles:</strong> {{ hebergement.nombre_chambres_disponibles }}</p>
        </div>
        <a href="{% url 'mes_reservations_hebergements' %}" class="retour">Retour</a>
    </div>
</body>
</html>

travel_planner/templates/reservation/detail_reservation_voyage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détails du voyage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Détails du voyage :</h1>
        <div class="details-box">
            <h2>{{ voyage.titre }}</h2>
            <br>
            <p><strong>Date de départ:</strong> {{ voyage.date_depart|date:"d/m/Y à H:i" }}</p>
            <p><strong>Date d'arrivée:</strong> {{ voyage.date_arrivee|date:"d/m/Y à H:i" }}</p>
            <br>
            <p><strong>Départ:</strong> {{ voyage.ville_depart }} - {{ voyage.lieu_depart }}</p>
            <p><strong>Arrivée:</strong> {{ voyage.ville_arrivee }} - {{ voyage.lieu_arrivee }}</p>
            <br>
            {% if voyage.mode_transport %}
                {% if voyage.mode_transport == "TR" %}
                    <p><strong>Mode de transport:</strong> Train</p>
                {% elif voyage.mode_transport == "AV" %}
                    <p><strong>Mode de transport:</strong> Avion</p>
                {% elif voyage.mode_transport == "VO" %}
                    <p><strong>Mode de transport:</strong> Voiture</p>
                {% else %}
                    <p><strong>Mode de transport:</strong> Inconnu</p>
                {% endif %}
            {% endif %}
        </div>
        <a href="{% url 'mes_reservations_voyages' %}" class="retour">Retour</a>
    </div>
</body>
</html>

travel_planner/templates/reservation/mes_reservations_hebergements.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Réservations d'hebergement</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Mes Réservations d'hebergement:</h1>
        <ul>
            {% for reservation in reservations %}
                {% if reservation.hebergement %}
                <li>
                    <a href="{% url 'reservation_hebergement'  reservation.hebergement.id %}"><strong>{{ reservation.hebergement }}</strong> le {{reservation.date_reservation|date:"d/m à H:i" }}</a>
                    <a href="{% url 'supprimer_reservation'  reservation.id %}" class="cancel">Annuler</a>
                </li>
                {% endif %}
            {% empty %}
                <li>Aucune réservation trouvée</li>
            {% endfor %}
        </ul>
        <a href="{% url 'choix_reservation' %}" class="retour">Retour</a>
    </div>
</body>
</html>

travel_planner/templates/reservation/mes_reservations_voyages.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Réservations de voyage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Mes Réservations de voyage:</h1>
        <ul>
            {% for reservation in reservations %}
                {% if reservation.voyage %}
                <li>
                    <a href="{% url 'reservation_voyage'  reservation.voyage.id %}"><strong>{{ reservation.voyage }}</strong> le {{reservation.date_reservation|date:"d/m à H:i" }}</a>
                    <a href="{% url 'supprimer_reservation'  reservation.id %}" class="cancel">Annuler</a>
                </li>
                {% endif %}
            {% empty %}
                <li>Aucune réservation trouvée</li>
            {% endfor %}
        </ul>
        <a href="{% url 'choix_reservation' %}" class="retour">Retour</a>
    </div>
</body>
</html>